### PR TITLE
connect wallet modal, footer, other css changes

### PR DESCRIPTION
**Pull request by slothtoday**
Connect wallet popup:
Screenshot 2022-03-25 at 11 51 00 PM
Footer:
Screenshot 2022-03-25 at 11 51 09 PM

### CODE REVIEW

**Comment by JSeam2** [comment]
It's looking generally good. Let me know if you need help integrating the web3 connections. I guess right now it's just the styling that's being done. 

**Some feedback**
The alignment and styling on the navbar looks wonky at the moment. It's a minor styling issue but kinda weird to look at. 
1. The Zesty text beside the logo should be a few px higher
2. The buttons on the left should be left aligned.
3. The border radius on buttons on the left aren't the same. Border radius on the square button changes upon mouse over.  For the outlined buttons it might be good to think of a better mouse over interaction. For example, filling in the background with a dark orange background with 50% opacity.
4. Responsive design isn't done just yet (but this is fine because misto hasn't come back with designs)

Here's the screenshot for reference
Screen Shot 2022-03-27 at 12 49 57 AM

Thanks for the help!

**Comment by slothtoday** [comment]
@JSeam2 The buttons with gradient border cannot have a border radius, I tried multiple ways. Maybe we could skip the gradient colour in the border and take a solid one there?

**Comment by slothtoday** [comment]
@JSeam2 
On hover:
Screenshot 2022-04-14 at 8 13 47 PM

**Comment by slothtoday** [comment]
@JSeam2 @Srile 
Can we merge this now?

**Comment by JSeam2** [comment]
LGTM!

**Pull request merged**
